name: Release CI
on:
  push:
    branches:
      - master
jobs:
  Create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
      # Verbose
      - name: Print full context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"  
      - name: Print release name 
        env:
          SUPPORTED_IMAGE: ${{ github.event.head_commit.message }}
        run: echo "$SUPPORTED_IMAGE"
      # # Docker Hub Login
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Docker Hub Push
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:${{ github.event.head_commit.message }}
      # Verbose
      - name: Print image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      # Create Release
      - uses: ncipollo/release-action@v1   
        with:
          tag: ${{ github.event.head_commit.message }}
          token: ${{ secrets.G_TOKEN }}           